package com.proyectoFinal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RailWayGranadaApplication {

	public static void main(String[] args) {
		SpringApplication.run(RailWayGranadaApplication.class, args);
	}

}

//AUTOMATICALLY GENERATED BY SPRINGBOOT
